### ISSUE TITLE
about translation of 'stack'

### ISSUE THREAD

**Issue by pyeonch** [Jaehyuk-Lee/cactbot#2]
다름이아니라 response.js에서 의 stack과 stack에 관련된 코드들은 집합으로 되어있어서, 제가 번역할 일이 있을 때 집합이라는 말을 써왔는데, 오늘 홍련 리퀘올리신거보니 셰어로 쓰신걸 봤습니다.
 집합과 셰어의 단어선택 기준을 여쭈어봐도 될까요?

제생각엔 같은말이고, 유저들은 셰어를 더 자주쓰는거같습니다.

**Comment by Jaehyuk-Lee** [comment]
아 제가 제 레포에 와치를 안걸어놔서 이슈가 올라왔는지도 몰랐네요.

stack이 쉐어의 의미로 쓰이지 않는 때가 있던걸로 기억합니다. (쉐어는 파티원이 모여서 데미지 나눠서 맞는 기믹을 지칭하죠.)
stack이 단순히 파티원끼리 모이라는 뜻인데, 그래서 장판을 모여서 뺀다거나 (각성 3층 중앙에 모여서 장판 빼는거) 그런 경우도 이 한가지 response로 처리해서 두 경우의 의미를 모두 포괄할 수 있는 집합이라는 설명을 적었습니다.

`id: 'E3S Drenching Pulse'` 여기서는 response를 쓰지 않았지만 쓰자면 Response.stack()으로 대체할 수 있었겠죠. Bait puddle 이라는 글자가 없었다면요.
```
      infoText: {
        en: 'Stack, Bait Puddles',
        de: 'Sammeln, Flächen ködern',
        fr: 'Packez, évitez les zones au sol',
        ja: '集合',
        cn: '集合',
        ko: '모이기',
      },
```

**Comment by pyeonch** [comment]
아하 그런경우도 stack을 사용하고있군요..이해했습니다!
그런 이유라면 response을 쓰지않은 stack을 번역할때는 쉐어로 번역해도 무방하겠군요
